### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by myesaya** [ds4owd-001/md-02-assignments-myesaya#1]
I have completed exercise 2 @larnsce , @mianzg , @sskorik01. I have a question. When making boxplots, we were asked to remove outliers. 

- Is it a requirement to remove outliers in a boxplot? And if it is not a requirement, which one is the best option?Thanks

**Comment by larnsce** [comment]
Thanks for your question, @myesaya.

It depends on what you want to achieve. Sometimes, removing outliers is useful when you display the individual points anyways (e.g. combination with `geom_jitter()`. Sometimes, you definitely want to keep the outliers displayed if you want to highlight them.

Also note that we have only removed the outliers from the visual display on the plot. They are still in the data that you used to for the boxplot and therefore have an influence on the median and boxplot itself. If you wanted to fully remove them, then you need to first use `filter()` on the data to remove the values that are outliers.
